apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-pods-to-sa
subjects:
  - kind: ServiceAccount
    name: cron-job
roleRef:
  kind: Role
  name: modify-pods
  apiGroup: rbac.authorization.k8s.io