apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fsx-sc
provisioner: fsx.csi.aws.com
parameters:
  fileSystemId: fs-04c243dd3dcd7a732 # Replace with your FSx file system ID
  subnetId: subnet-09bf032d4e5a6c038  # Replace with your subnet ID
  securityGroupIds: sg-02d181ea45a5373e3  # Replace with your security group ID