apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  capacity:
    storage: 1200Gi  # Adjust based on your FSx volume size
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fsx-sc
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-04c243dd3dcd7a732  # Replace with your FSx file system ID
    volumeAttributes: 
      dnsname: fs-04c243dd3dcd7a732.fsx.us-east-2.amazonaws.com      # Replace with your FSx file system DNS name
      mountname: rikurbev   # Replace with your FSx file system DNS name

