apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fsx-sc
provisioner: fsx.csi.aws.com
parameters:
  fileSystemId: ${FILESYSTEM_ID} # Replace with your FSx file system ID
  subnetId: ${SUBNET_ID}  # Replace with your subnet ID
  securityGroupIds: ${SECURITYGROUP_ID}  # Replace with your security group ID