apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fsx-sc
provisioner: fsx.csi.aws.com
parameters:
  fileSystemId: fs-xxxx # Replace with your FSx file system ID
  subnetId: subnet-xxxxx  # Replace with your subnet ID
  securityGroupIds: sg-xxxxx  # Replace with your security group ID